import { apiClient } from './http';

export interface CheckoutResponse {
  sessionId: string;
  sessionUrl?: string;
  bookingId: string;
}

export async function initiateCheckout(flightId: string, seatNumber: string) {
  try {
    // Call backend to create checkout session
    const response = await apiClient.post<CheckoutResponse>('/api/payments/checkout', {
      flightId,
      seatNumber,
    });

    const { sessionUrl } = response.data;

    // Redirect to Stripe-hosted URL generated by backend.
    if (sessionUrl) {
      window.location.href = sessionUrl;
      return;
    }

    throw new Error('Payment URL unavailable');
  } catch (err) {
    throw err instanceof Error ? err : new Error(String(err));
  }
}
